# Лабораторная работа № 5
## Вариант №8
### Клейменов Владимир, БПМ-19-3

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
%matplotlib inline

In [10]:
df = pd.read_csv("./var8.csv")
df

           V1         V2
0   10.057199   1.414387
1    9.873437  -1.335898
2   10.360877   0.579584
3    9.627398  -0.361821
4   10.169106  -0.046852
5   10.068334  -0.599477
6   10.004556   0.215104
7    9.877720   0.093631
8    9.947895  -2.119834
9   10.361134   0.852443
10   9.980600  15.154375
11   9.923103  14.028138
12   9.824328  13.898572
13   9.900884  14.309755
14   9.983142  13.416365
15   9.728456  15.137766
16  10.228540  16.502344
17  10.019565  15.192882
18  10.293004  15.527155
19  10.198087  13.516794

In [11]:
X = df.values
X

array([[10.05719861,  1.41438675],
       [ 9.87343699, -1.33589777],
       [10.3608769 ,  0.57958364],
       [ 9.62739781, -0.36182121],
       [10.16910568, -0.04685245],
       [10.06833354, -0.59947747],
       [10.00455552,  0.21510449],
       [ 9.87772   ,  0.09363149],
       [ 9.94789465, -2.11983442],
       [10.36113406,  0.85244309],
       [ 9.98060015, 15.15437457],
       [ 9.92310266, 14.02813836],
       [ 9.82432757, 13.89857216],
       [ 9.9008843 , 14.30975511],
       [ 9.98314151, 13.41636508],
       [ 9.72845559, 15.13776607],
       [10.22853956, 16.50234395],
       [10.01956541, 15.19288159],
       [10.29300421, 15.52715473],
       [10.19808717, 13.51679371]])

In [12]:
model = KMeans(n_clusters=3)

In [13]:
model.fit(X)

/home/kleymenov/Projects/University/psa-labs/venv/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3)

In [14]:
all_predictions = model.predict(X)

In [15]:
print(all_predictions)

[1 1 1 1 1 1 1 1 1 1 2 0 0 0 0 2 2 2 2 0]

In [16]:
df1 = pd.DataFrame(all_predictions)
df1.rename(columns={0: 'Cluster'}, inplace=True)
df1 = pd.concat([df, df1], axis=1)
df1

           V1         V2  Cluster
0   10.057199   1.414387        1
1    9.873437  -1.335898        1
2   10.360877   0.579584        1
3    9.627398  -0.361821        1
4   10.169106  -0.046852        1
5   10.068334  -0.599477        1
6   10.004556   0.215104        1
7    9.877720   0.093631        1
8    9.947895  -2.119834        1
9   10.361134   0.852443        1
10   9.980600  15.154375        2
11   9.923103  14.028138        0
12   9.824328  13.898572        0
13   9.900884  14.309755        0
14   9.983142  13.416365        0
15   9.728456  15.137766        2
16  10.228540  16.502344        2
17  10.019565  15.192882        2
18  10.293004  15.527155        2
19  10.198087  13.516794        0

In [17]:
print(model.cluster_centers_)

[[ 9.96590864 13.83392488]
 [10.03476538 -0.13087339]
 [10.05003298 15.50290418]]

In [18]:
from scipy.stats import f_oneway

datav1 = df['V1'].to_numpy()
datav2 = df['V2'].to_numpy()

datav1_c1 = datav1[all_predictions == 0]
datav1_c2 = datav1[all_predictions == 1]
datav1_c3 = datav1[all_predictions == 2]

datav2_c1 = datav2[all_predictions == 0]
datav2_c2 = datav2[all_predictions == 1]
datav2_c3 = datav2[all_predictions == 2]

print(f_oneway(datav1_c1, datav1_c2, datav1_c3))
print(f_oneway(datav2_c1, datav2_c2, datav2_c3))

F_onewayResult(statistic=0.2451144180853817, pvalue=0.7853335522666638)
F_onewayResult(statistic=806.7603301827759, pvalue=1.4257462224669592e-17)

Переменные по которым были обнаруженны значимые различия между выделенными кластерами: V2 (pvalue < 0.05)

In [19]:
pca = PCA(n_components=2)

def get_pc(df):
    return df.assign(PC1=pca.fit_transform(df)[:, 0],
           PC2=pca.fit_transform(df)[:, 1])

df2 = get_pc(df)
df2

           V1         V2       PC1       PC2
0   10.057199   1.414387  5.854397 -0.033583
1    9.873437  -1.335898  8.604611  0.151234
2   10.360877   0.579584  6.689317 -0.336941
3    9.627398  -0.361821  7.630440  0.396899
4   10.169106  -0.046852  7.315679 -0.144930
5   10.068334  -0.599477  7.868265 -0.043945
6   10.004556   0.215104  7.053659  0.019520
7    9.877720   0.093631  7.175083  0.146402
8    9.947895  -2.119834  9.388576  0.077077
9   10.361134   0.852443  6.416457 -0.337303
10   9.980600  15.154375 -7.885619  0.037741
11   9.923103  14.028138 -6.759405  0.095671
12   9.824328  13.898572 -6.629877  0.194496
13   9.900884  14.309755 -7.041030  0.117781
14   9.983142  13.416365 -6.147609  0.035867
15   9.728456  15.137766 -7.869107  0.289892
16  10.228540  16.502344 -9.233493 -0.210716
17  10.019565  15.192882 -7.924111 -0.001239
18  10.293004  15.527155 -8.258279 -0.274806
19  10.198087  13.516794 -6.247955 -0.179117

In [20]:
def get_pca2(df, threshold=0.9):
    pca = PCA()
    fit = pca.fit_transform(df)
    n_components = sum(np.cumsum(pca.explained_variance_ratio_) < threshold) + 1
    summ = 0
    k = 0
    for a in pca.explained_variance_ratio_:
        print(float(a))
        if summ < 0.9:
            summ+=float(a)
            k+=1
    print()
    print(k,"- Минимальное количество компонент для обьяснения 90% изменчивости")
    print()
    return pd.concat([df, pd.DataFrame(fit[:, :n_components])], axis=1)

print(get_pca2(df2))

0.9993188182220005
0.0006811817779995165
9.522452229199062e-33
1.0378646740693875e-33

1 - Минимальное количество компонент для обьяснения 90% изменчивости

           V1         V2       PC1       PC2          0
0   10.057199   1.414387  5.854397 -0.033583   8.279368
1    9.873437  -1.335898  8.604611  0.151234  12.168757
2   10.360877   0.579584  6.689317 -0.336941   9.460122
3    9.627398  -0.361821  7.630440  0.396899  10.791072
4   10.169106  -0.046852  7.315679 -0.144930  10.345933
5   10.068334  -0.599477  7.868265 -0.043945  11.127408
6   10.004556   0.215104  7.053659  0.019520   9.975380
7    9.877720   0.093631  7.175083  0.146402  10.147100
8    9.947895  -2.119834  9.388576  0.077077  13.277452
9   10.361134   0.852443  6.416457 -0.337303   9.074241
10   9.980600  15.154375 -7.885619  0.037741 -11.151949
11   9.923103  14.028138 -6.759405  0.095671  -9.559242
12   9.824328  13.898572 -6.629877  0.194496  -9.376062
13   9.900884  14.309755 -7.041030  0.117781  -9.957520
14   9.983142  13.416365 -6.147609  0.035867  -8.694032
15   9.728456  15.137766 -7.869107  0.289892 -11.128598
16  10.228540  16.502344 -9.233493 -0.210716 -13.058131
17  10.019565  15.192882 -7.924111 -0.001239 -11.206385
18  10.293004  15.527155 -8.258279 -0.274806 -11.678971
19  10.198087  13.516794 -6.247955 -0.179117  -8.835942

In [21]:
def is_multicol(df):
  corr = df.corr()
  triu= pd.DataFrame(np.triu(corr,k=0))
  per = []
  for i in range(0, len(corr)):
    for j in range(0, len(corr)):
      if (triu.iloc[i,j]==1) & (i != j):
        per.append(j+1)
        per.append(i+1)
  if per == []:
    print("There is no collinearity in the data")
  else:
    i=0
    while i < len(per):
      print('V'+str(per[i])+' '+'V'+str(per[i+1]),end=' ')
      i += 2
is_multicol(df)

There is no collinearity in the data